### ISSUE TITLE
Sample with GPIO interrupt

### ISSUE THREAD

**Issue by skanico** [espressif/esp-apple-homekit-adk#15]
Hello,
Would you have a sample with GPIO interrupt handling?
Thanks!

**Comment by odx** [comment]
What‘s wrong with the [esp idf gpio](https://github.com/espressif/esp-idf/tree/master/examples/peripherals/gpio)  example?

**Comment by skanico** [comment]
In the meantime, I succeeded with another code. Thanks anyway!
